# Generated by Django 6.1.1 on 2026-09-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CentreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.diagnosticcentre')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.diagnostictest')),
            ],
            options={
                'ordering': ['test__name'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticcentre',
            name='tests',
            field=models.ManyToManyField(related_name='centres', through='catalog.CentreTest', to='catalog.diagnostictest'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticcentre',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='uniq_centre_name_city'),
        ),
        migrations.AddConstraint(
            model_name='centretest',
            constraint=models.UniqueConstraint(fields=('centre', 'test'), name='uniq_centre_test'),
        ),
        migrations.AddConstraint(
            model_name='centretest',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='centre_test_price_positive'),
        ),
    ]
